import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'hi' | 'kn';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Common
    'common.continue': 'Continue',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.cancel': 'Cancel',
    'common.submit': 'Submit',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.all': 'All',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.ok': 'OK',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    
    // Navigation
    'nav.home': 'Home',
    'nav.market': 'Market',
    'nav.traders': 'Traders',
    'nav.sell': 'Sell',
    'nav.buy': 'Buy',
    'nav.chat': 'Chat',
    'nav.profile': 'Profile',
    'nav.verification': 'Verification',
    'nav.disputes': 'Disputes',
    'nav.prices': 'Prices',
    'nav.schemes': 'Schemes',
    
    // Auth
    'auth.enterMobile': 'Enter Mobile Number',
    'auth.verifyOtp': 'Verify OTP',
    'auth.selectRole': 'Select Your Role',
    'auth.farmer': 'I am a Farmer',
    'auth.trader': 'I am a Trader',
    'auth.sendOtp': 'Send OTP',
    'auth.verifyOtpBtn': 'Verify OTP',
    'auth.resendOtp': 'Resend OTP',
    'auth.farmerDesc': 'Sell your produce directly',
    'auth.traderDesc': 'Buy produce from farmers',
    
    // Dashboard
    'dashboard.welcome': 'Welcome Farmer!',
    'dashboard.welcomeTrader': 'Welcome Trader!',
    'dashboard.activeProducts': 'Active Products',
    'dashboard.newBids': 'New Bids',
    'dashboard.availableProduce': 'Available Produce',
    'dashboard.activeBids': 'Active Bids',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.sellProduce': 'Sell Produce',
    'dashboard.marketPrices': 'Market Prices',
    'dashboard.schemes': 'Schemes',
    'dashboard.todayPrices': "Today's Market Prices",
    'dashboard.myListedProduce': 'My Listed Produce',
    'dashboard.recentActivity': 'Recent Activity',
    
    // Market
    'market.title': 'Market Prices',
    'market.liveTitle': 'Live Market Prices',
    'market.searchPlaceholder': 'Search crops or mandi',
    'market.rising': 'Rising',
    'market.falling': 'Falling',
    'market.stable': 'Stable',
    'market.list': 'List',
    'market.compare': 'Compare',
    'market.highest': 'Highest',
    'market.average': 'Average',
    'market.lowest': 'Lowest',
    'market.mandiPrices': 'Mandi-wise Prices',
    
    // Add Produce
    'addProduce.title': 'Sell Your Produce',
    'addProduce.cropDetails': 'Crop Details',
    'addProduce.pricing': 'Set Your Price',
    'addProduce.locationImages': 'Location & Images',
    'addProduce.review': 'Review & Submit',
    'addProduce.cropName': 'Crop Name',
    'addProduce.variety': 'Variety',
    'addProduce.quantity': 'Quantity',
    'addProduce.minPrice': 'Minimum Price',
    'addProduce.location': 'Location',
    'addProduce.takePhoto': 'Take Photo',
    'addProduce.addToListing': 'Add to Listing',
    
    // Bidding
    'bidding.title': 'Place Your Bid',
    'bidding.currentBids': 'Current Bids',
    'bidding.placeBid': 'Place Bid',
    'bidding.bidAmount': 'Bid Amount',
    'bidding.message': 'Message (Optional)',
    'bidding.submitBid': 'Submit Bid',
    'bidding.noBids': 'No bids yet - be the first!',
    'bidding.highest': 'Highest',
    'bidding.totalBids': 'Total Bids',
    'bidding.suggestedBid': 'Suggested Bid',
    'bidding.acceptTitle': 'Accept Bid',
    'bidding.acceptBidBtn': 'Accept Bid',
    'bidding.acceptWarning': 'Accepting this bid will reject all other offers and mark this listing as sold.',
   
    // Chat
    'chat.typeMessage': 'Type message...',
    'chat.online': 'Online',
    'chat.startConversation': 'Start conversation',
    'chat.quickReplies': 'Quick Replies',
    'chat.interested': 'Yes, I am interested',
    'chat.whatPrice': 'What is the price?',
    'chat.whenMeet': 'When can we meet?',
    'chat.thankYou': 'Thank you',
    'chat.okay': 'Okay',
    'chat.talkTomorrow': "Let's talk tomorrow",
    
    // Profile
    'profile.title': 'Profile',
    'profile.phoneNumber': 'Phone Number',
    'profile.type': 'Type',
    'profile.farmer': 'Farmer',
    'profile.trader': 'Trader',
    'profile.verificationStatus': 'Verification Status',
    'profile.verified': 'Verified',
    'profile.notVerified': 'Not Verified',
    'profile.viewSchemes': 'View Government Schemes',
    
    // Government Schemes
    'schemes.title': 'Government Schemes',
    'schemes.searchPlaceholder': 'Search schemes',
    'schemes.eligibility': 'Eligibility',
    'schemes.benefits': 'Benefits',
    'schemes.applyNow': 'Apply Now',
    'schemes.subsidy': 'Subsidy',
    'schemes.loan': 'Loan',
    'schemes.insurance': 'Insurance',
    'schemes.training': 'Training',
    
    // Transaction
    'transaction.title': 'Transaction Tracking',
    'transaction.orderId': 'Order ID',
    'transaction.amount': 'Amount',
    'transaction.quantity': 'Quantity',
    'transaction.progress': 'Progress',
    'transaction.pending': 'Pending',
    'transaction.confirmed': 'Confirmed',
    'transaction.inTransit': 'In Transit',
    'transaction.delivered': 'Delivered',
    'transaction.completed': 'Completed',
    'transaction.needHelp': 'Need Help?',
    'transaction.contact': 'Contact',
    'transaction.summary': 'Transaction Summary',
    'transaction.dealConfirmation': 'Deal Confirmation',
    'transaction.produce': 'Produce',
    'transaction.rate': 'Rate',
    'transaction.farmer': 'Farmer',
    'transaction.trader': 'Trader',
    'transaction.location': 'Location',
    'transaction.qualityGuarantee': 'Quality Guarantee',
    'transaction.qualityGuaranteeDesc': 'Produce quality is verified by the platform. Full refund if quality is not as expected.',
    'transaction.status': 'Status',
    'transaction.trackProgress': 'Track your transaction progress',
    'transaction.details': 'Details',
    'transaction.viewDetails': 'View Details',
    'transaction.hideDetails': 'Hide Details',
    'transaction.paymentBreakdown': 'Payment Breakdown',
    'transaction.produceValue': 'Produce Value',
    'transaction.platformFee': 'Platform Fee',
    'transaction.securePayment': 'Secure Payment',
    'transaction.securePaymentDesc': 'Your payment is secure in escrow. Farmer will be paid only after produce confirmation.',
    'transaction.collectionInfo': 'Collection Information',
    'transaction.pickupLocation': 'Pickup Location',
    'transaction.vehicleDetails': 'Vehicle Details',
    'transaction.driverContact': 'Driver Contact',
    'transaction.receipt': 'Receipt',
    'transaction.download': 'Download',
    'transaction.dealAccepted': 'Deal Accepted',
    'transaction.produceCollected': 'Produce Collected',
    'transaction.paymentInitiated': 'Payment Initiated',
    'transaction.paymentCompleted': 'Payment Completed',
    'transaction.perQuintal': 'per quintal',
    'transaction.qualityCheck': 'Quality Check',
    'transaction.weightVerified': 'Weight Verified',
    'transaction.collection': 'Collection',
    'transaction.utrNumber': 'UTR Number',
    'transaction.farmerAccount': 'Farmer Account',
    'transaction.paymentStatus': 'Payment Status',
    'transaction.success': 'Success',
    'transaction.quintal': 'quintal',
    'transaction.deliveryInfo': 'Delivery Information',
    'transaction.hide': 'Hide',
    'transaction.track': 'Track',
    'transaction.liveTracking': 'Live Tracking',
    'transaction.currentLocation': 'Current Location',
    'transaction.estimatedArrival': 'Estimated Arrival',
    'transaction.hours': 'hours',
    'transaction.journeyComplete': 'journey complete',
    'transaction.invoice': 'Invoice',
    'transaction.qualityCertificate': 'Quality Certificate',
    'transaction.rateTransaction': 'Rate Transaction',
    'transaction.rateFarmer': 'Rate the Farmer',
    'transaction.feedback': 'Feedback (Optional)',
    'transaction.shareExperience': 'Share your experience...',
    'transaction.submitRating': 'Submit Rating',
    'transaction.qualityStatus': 'Quality Status',
    'transaction.checkComplete': 'Check Complete - As per standards',
    'transaction.farmerContact': 'Farmer Contact',
    'transaction.supportCenter': 'Support Center',
    'transaction.transportCost': 'Transport Cost',
    'transaction.bankTransfer': 'Bank Transfer',
    'order.tracking': 'Order Tracking',
    'order.placed': 'Order Placed',
    'order.confirmed': 'Confirmed',
    'order.pendingPayment': 'Payment Pending',
    'order.dispatched': 'Dispatched',
    'order.delivered': 'Delivered',
    'order.paid': 'Payment Released',
    'order.disputed': 'Disputed',
    'order.status.placedDesc': 'Waiting for farmer to confirm',
    'order.status.confirmedDesc': 'Farmer accepted the order',
    'order.status.pendingPaymentDesc': 'Awaiting payment from trader',
    'order.status.dispatchedDesc': 'Produce is on the way',
    'order.status.deliveredDesc': 'Trader confirmed receipt',
    'order.status.paidDesc': 'Payment sent to farmer',
    'order.status.disputedDesc': 'Under dispute resolution',
    'order.confirmOrder': 'Confirm Order',
    'order.markDispatched': 'Mark as Dispatched',
    'order.confirmDelivery': 'Confirm Delivery Received',
    'order.payNow': 'Pay Now',
    'order.history': 'Order History',
    'order.raiseDispute': 'Raise a dispute',
    'order.dispatchDetails': 'Dispatch Details',
    'order.vehicleNo': 'Vehicle No.',
    'order.deliveryProof': 'Delivery Proof',
    'order.rateOrder': 'Rate Order',
    'order.submitDispute': 'Submit Dispute',
    'order.confirmDispatch': 'Confirm Dispatch',
    'order.transportDetails': 'Transport Details',
    'order.confirmAndPay': 'Confirm & Proceed to Pay',
    'order.disputeUnderReview': 'Dispute Under Review',
    'order.disputeReviewDesc': 'Our team is investigating. You will receive a resolution within 24 hours.',
    'trader.myBids': 'My Bids',
    'trader.myBidsDesc': 'My Active & Past Bids',
    'trader.totalBids': 'total bids placed',
    'trader.noBids': 'No bids placed yet',
    'trader.visitMarketplace': 'Visit the marketplace to place your first bid',
    'trader.yourBid': 'Your Bid',
    'trader.hoursAgo': 'h ago',
    'trader.daysAgo': 'd ago',
    'trader.justNow': 'Just now',
    'common.rejected': 'Rejected',
    'common.accepted': 'Accepted',
    'order.myOrders': 'My Orders',
    'order.purchases': 'Your Purchases',
    'order.completedDeals': 'Your Completed Deals',
    'order.noOrders': 'No orders yet',
    'order.noOrdersDesc': 'Orders appear here after a bid is accepted',
    'order.trader': 'Trader',
    'order.paidLabel': 'Paid',
    'order.loadingOrders': 'Loading your orders...',
    'order.loadingHistory': 'Loading order history...',
    'bank.addAccount': 'Add Bank Account',
    'bank.chooseBank': 'Choose your bank',
    'bank.enterDetails': 'Enter account details',
    'bank.verifyAccount': 'Verify your account',
    'bank.securityCheck': 'Security verification',
    'bank.searchBank': 'Search your bank...',
    'bank.popularBanks': 'Popular Banks',
    'bank.allBanks': 'All Banks',
    'bank.accountHolder': 'Account Holder Name',
    'bank.accountNumber': 'Account Number',
    'bank.confirmAccountNumber': 'Confirm Account Number',
    'bank.ifscCode': 'IFSC Code',
    'bank.accountType': 'Account Type',
    'bank.savings': 'Savings',
    'bank.current': 'Current',
    'bank.verifyMyAccount': 'Verify My Account',
    'bank.successTitle': 'Bank Account Added!',
    'bank.successDesc': 'Your account has been verified and registered.',
    'bank.continueDashboard': 'Continue to Dashboard',
    'produce.addTitle': 'Add Produce to Sell',
    'produce.cropName': 'Crop Name',
    'produce.selectCrop': 'Select Crop',
    'produce.variety': 'Variety',
    'produce.quantity': 'Quantity',
    'produce.expectedPrice': 'Expected Price',
    'produce.images': 'Produce Images',
    'produce.selectFiles': 'Select Files',
    'produce.maxImages': 'Maximum 5 images allowed',
    'produce.locationPlaceholder': 'village, tehsil, district',
    'produce.detectLocation': 'Detect Location',
    'produce.detecting': 'Detecting...',
    'produce.description': 'Description',
    'produce.descPlaceholder': 'quality, features...',
    'produce.listProduce': 'List Produce',
    'produce.fillAllFields': 'Please fill all required fields',
    'farmer.verifyTitle': 'Account Verification Required',
    'farmer.verifyPending': 'Your documents are currently being reviewed by an Admin. You will be able to access the marketplace once approved.',
    'farmer.verifyRequired': 'You cannot access marketplace features until your identity is verified. Please navigate to the Profile Tab below to upload your KYC documents.',
    'farmer.uploadId': 'Go to the "Profile" Tab below to upload your ID!',
    'farmer.activeListings': 'Active Listings & Bids',
    'farmer.receivedBids': 'Received Bids',
    'farmer.ordersPayments': 'Orders & Payments',
    'farmer.totalEarnings': 'Total Earnings',
    'farmer.noListings': 'No active listings found.',
    'farmer.acceptBidTitle': 'Accept Bid?',
    'farmer.acceptBidMessage': 'Accepting this bid will finalize the deal and reject all other offers for this listing. Continue?',
    'farmer.confirmPaymentTitle': 'Confirm Payment Receipt',
    'farmer.confirmPaymentMessage': 'Confirm that you have securely received the payment in your bank account?',
    'farmer.disputeTitle': 'Payment Dispute',
    'farmer.disputeMessage': 'Report this payment as NOT received? This will flag the order for dispute.',
    'farmer.paymentReceivedDesc': 'The Trader has completed the Razorpay checkout! Please confirm receipt.',
    'trader.payConfirm': 'Proceed to pay ₹{amount} for this order via Razorpay?',
    'trader.razorpayFail': 'Razorpay SDK failed to load. Are you online?',
    'trader.paymentTitle': 'Payment for Order',
    'trader.verifyTitle': 'Account Verification Required',
    'trader.verifyPending': 'Your documents are being reviewed by an Admin. Please wait for approval.',
    'trader.verifyRequired': 'You cannot access marketplace features until your identity is verified. Please navigate to the Profile Tab below to upload your KYC documents.',
    'trader.uploadId': 'Go to the "Profile" Tab below to upload your ID!',
    'trader.activeOrders': 'Active Orders & Shipments',
    'trader.noOrders': 'No active transactions found.',
    'trader.payNow': 'Pay Now',
    'trader.paid': 'Paid',
    'trader.marketPulse': 'Market Pulse',
    'trader.noProduce': 'No new produce listed yet.',
    'trader.availableProduces': 'Available Produce',
    'trader.searchPlaceholder': 'Search crops, variety or location...',
    'trader.filters': 'Filters',
    'trader.verifiedOnly': 'Verified Only',
    'trader.advancedFilters': 'Advanced Filters',
    'trader.cropType': 'Crop Type',
    'trader.allCrops': 'All Crops',
    'trader.allLocations': 'All Locations',
    'trader.quantityRange': 'Quantity Range',
    'trader.priceRange': 'Price Range',
    'trader.min': 'Min',
    'trader.max': 'Max',
    'trader.sortBy': 'Sort By',
    'trader.newest': 'Newest First',
    'trader.priceLow': 'Price: Low to High',
    'trader.priceHigh': 'Price: High to Low',
    'trader.clearFilters': 'Clear All Filters',
    'trader.quickStats': 'Quick Stats',
    'trader.minPrice': 'Min Price',
    'trader.maxPrice': 'Max Price',
    
    // Language Selection
    'language.chooseLanguage': 'Choose Your Language',
    'language.selectSubtitle': 'Please select your preferred language',
    'language.voiceAssistance': 'Voice Assistance Available',
    'language.tapSpeaker': 'Tap the speaker icon for audio help',

    // Farmer Dashboard
    'farmer.noConfirmedOrders': 'No confirmed orders yet.',
    'farmer.active': 'Active',
    'farmer.accept': 'Accept',
    'farmer.accepting': 'Accepting...',
    'farmer.yesReceived': 'Yes, Received',
    'farmer.notReceived': 'Not Received',
    'farmer.basePrice': 'Base Price',
    'farmer.amount': 'Amount',
    'farmer.trader': 'Trader',
    'farmer.phone': 'Phone',
    'farmer.orderDate': 'Order Date',
    'farmer.messageTrader': 'Message Trader',

    // Trader Dashboard
    'trader.welcome': 'Welcome Trader!',
    'trader.purchaseTracking': 'Purchase Tracking',
    'trader.activeBids': 'Active Bids',
    'trader.availableInMarket': 'Available in Market',
    'trader.noTransactions': 'No transactions available.',
    'trader.dealDetails': 'Deal Details',
    'trader.paymentConfirmed': 'Payment Confirmed',
    'trader.awaitingConfirmation': 'Awaiting Farmer Confirmation',
    'trader.paymentDisputed': 'Payment Disputed',
    'trader.pendingPayment': 'Pending Payment',
    'trader.messageFarmer': 'Message Farmer',
  },
  hi: {
    // Common
    'common.continue': 'जारी रखें',
    'common.back': 'पिछला',
    'common.next': 'अगला',
    'common.previous': 'पिछला',
    'common.cancel': 'रद्द करें',
    'common.submit': 'जमा करें',
    'common.save': 'सेव करें',
    'common.edit': 'संपादित करें',
    'common.delete': 'हटाएं',
    'common.search': 'खोजें',
    'common.filter': 'फिल्टर',
    'common.all': 'सभी',
    'common.yes': 'हाँ',
    'common.no': 'नहीं',
    'common.ok': 'ठीक है',
    'common.loading': 'लोड हो रहा है...',
    'common.error': 'त्रुटि',
    'common.success': 'सफलता',
    
    // Navigation
    'nav.home': 'होम',
    'nav.market': 'बाज़ार',
    'nav.traders': 'व्यापारी',
    'nav.sell': 'बेचें',
    'nav.buy': 'खरीदें',
    'nav.chat': 'चैट',
    'nav.profile': 'प्रोफ़ाइल',
    'nav.verification': 'सत्यापन',
    'nav.disputes': 'विवाद',
    'nav.prices': 'कीमतें',
    'nav.schemes': 'योजनाएं',
    
    // Auth
    'auth.enterMobile': 'मोबाइल नंबर दर्ज करें',
    'auth.verifyOtp': 'OTP सत्यापित करें',
    'auth.selectRole': 'अपनी भूमिका चुनें',
    'auth.farmer': 'मैं एक किसान हूं',
    'auth.trader': 'मैं एक व्यापारी हूं',
    'auth.sendOtp': 'OTP भेजें',
    'auth.verifyOtpBtn': 'OTP सत्यापित करें',
    'auth.resendOtp': 'OTP पुनः भेजें',
    'auth.farmerDesc': 'अपनी फसल सीधे बेचें',
    'auth.traderDesc': 'किसानों से फसल खरीदें',
    
    // Dashboard
    'dashboard.welcome': 'नमस्ते किसान भाई!',
    'dashboard.welcomeTrader': 'नमस्ते व्यापारी जी!',
    'dashboard.activeProducts': 'सक्रिय उत्पाद',
    'dashboard.newBids': 'नई बोलियां',
    'dashboard.availableProduce': 'उपलब्ध फसलें',
    'dashboard.activeBids': 'सक्रिय बोलियां',
    'dashboard.quickActions': 'त्वरित कार्य',
    'dashboard.sellProduce': 'फसल बेचें',
    'dashboard.marketPrices': 'मंडी भाव',
    'dashboard.schemes': 'योजनाएं',
    'dashboard.todayPrices': 'आज के बाज़ार भाव',
    'dashboard.myListedProduce': 'मेरी सूचीबद्ध फसलें',
    'dashboard.recentActivity': 'हाल की गतिविधि',
    
    // Market
    'market.title': 'मंडी भाव',
    'market.liveTitle': 'रियल टाइम कीमतें',
    'market.searchPlaceholder': 'फसल या मंडी खोजें',
    'market.rising': 'बढ़ते',
    'market.falling': 'गिरते',
    'market.stable': 'स्थिर',
    'market.list': 'सूची',
    'market.compare': 'तुलना',
    'market.highest': 'सर्वोच्च',
    'market.average': 'औसत',
    'market.lowest': 'न्यूनतम',
    'market.mandiPrices': 'मंडी-वार कीमतें',
    
    // Add Produce
    'addProduce.title': 'फसल बेचें',
    'addProduce.cropDetails': 'फसल का विवरण',
    'addProduce.pricing': 'कीमत निर्धारण',
    'addProduce.locationImages': 'स्थान और तस्वीरें',
    'addProduce.review': 'समीक्षा करें',
    'addProduce.cropName': 'फसल का नाम',
    'addProduce.variety': 'किस्म',
    'addProduce.quantity': 'मात्रा',
    'addProduce.minPrice': 'न्यूनतम कीमत',
    'addProduce.location': 'स्थान',
    'addProduce.takePhoto': 'तस्वीर लें',
    'addProduce.addToListing': 'सूची में जोड़ें',
    
    // Bidding
    'bidding.title': 'बोली लगाएं',
    'bidding.currentBids': 'वर्तमान बोलियां',
    'bidding.placeBid': 'बोली लगाएं',
    'bidding.bidAmount': 'बोली राशि',
    'bidding.message': 'संदेश (वैकल्पिक)',
    'bidding.submitBid': 'बोली जमा करें',
    'bidding.noBids': 'अभी तक कोई बोली नहीं - पहले बनें!',
    'bidding.highest': 'सर्वोच्च',
    'bidding.totalBids': 'कुल बोलियां',
    'bidding.suggestedBid': 'सुझावित बोली',
    'bidding.acceptTitle': 'बोली स्वीकार करें',
    'bidding.acceptBidBtn': 'बोली स्वीकार करें',
    'bidding.acceptWarning': 'इस बोली को स्वीकार करने से अन्य सभी प्रस्ताव खारिज हो जाएंगे और इस लिस्टिंग को बिका हुआ माना जाएगा।',

    // Chat
    'chat.typeMessage': 'संदेश लिखें...',
    'chat.online': 'ऑनलाइन',
    'chat.startConversation': 'बातचीत शुरू करें',
    'chat.quickReplies': 'त्वरित उत्तर',
    'chat.interested': 'हाँ, मुझे रुचि है',
    'chat.whatPrice': 'कीमत क्या है?',
    'chat.whenMeet': 'कब मिल सकते हैं?',
    'chat.thankYou': 'धन्यवाद',
    'chat.okay': 'ठीक है',
    'chat.talkTomorrow': 'कल बात करते हैं',
    
    // Profile
    'profile.title': 'प्रोफ़ाइल',
    'profile.phoneNumber': 'फ़ोन नंबर',
    'profile.type': 'प्रकार',
    'profile.farmer': 'किसान',
    'profile.trader': 'व्यापारी',
    'profile.verificationStatus': 'सत्यापन स्थिति',
    'profile.verified': 'सत्यापित',
    'profile.notVerified': 'गैर-सत्यापित',
    'profile.viewSchemes': 'सरकारी योजनाएं देखें',
    
    // Government Schemes
    'schemes.title': 'सरकारी योजनाएं',
    'schemes.searchPlaceholder': 'योजना खोजें',
    'schemes.eligibility': 'पात्रता',
    'schemes.benefits': 'लाभ',
    'schemes.applyNow': 'आवेदन करें',
    'schemes.subsidy': 'सब्सिडी',
    'schemes.loan': 'ऋण',
    'schemes.insurance': 'बीमा',
    'schemes.training': 'प्रशिक्षण',
    
    // Transaction
    'transaction.title': 'लेन-देन ट्रैकिंग',
    'transaction.orderId': 'ऑर्डर आईडी',
    'transaction.amount': 'राशि',
    'transaction.quantity': 'मात्रा',
    'transaction.progress': 'प्रगति',
    'transaction.pending': 'लंबित',
    'transaction.confirmed': 'पुष्ट',
    'transaction.inTransit': 'ट्रांजिट में',
    'transaction.delivered': 'डिलीवर',
    'transaction.completed': 'पूर्ण',
    'transaction.needHelp': 'सहायता चाहिए?',
    'transaction.contact': 'संपर्क करें',
    'transaction.summary': 'लेन-देन सारांश',
    'transaction.dealConfirmation': 'डील कन्फर्मेशन',
    'transaction.produce': 'फसल',
    'transaction.rate': 'दर',
    'transaction.farmer': 'किसान',
    'transaction.trader': 'व्यापारी',
    'transaction.location': 'स्थान',
    'transaction.qualityGuarantee': 'गुणवत्ता गारंटी',
    'transaction.qualityGuaranteeDesc': 'फसल की गुणवत्ता प्लेटफॉर्म द्वारा सत्यापित है। यदि गुणवत्ता अपेक्षा के अनुसार नहीं है तो पूर्ण धनवापसी।',
    'transaction.status': 'स्थिति',
    'transaction.trackProgress': 'अपनी लेनदेन प्रगति ट्रैक करें',
    'transaction.details': 'विवरण',
    'transaction.viewDetails': 'विवरण देखें',
    'transaction.hideDetails': 'छुपाएं',
    'transaction.paymentBreakdown': 'भुगतान विवरण',
    'transaction.produceValue': 'फसल मूल्य',
    'transaction.platformFee': 'प्लेटफॉर्म शुल्क',
    'transaction.securePayment': 'सुरक्षित भुगतान',
    'transaction.securePaymentDesc': 'आपका भुगतान एस्क्रो में सुरक्षित है। फसल की पुष्टि के बाद ही किसान को भुगतान होगा।',
    'transaction.collectionInfo': 'संग्रह जानकारी',
    'transaction.pickupLocation': 'संग्रह स्थान',
    'transaction.vehicleDetails': 'वाहन विवरण',
    'transaction.driverContact': 'ड्राइवर संपर्क',
    'transaction.receipt': 'रसीद',
    'transaction.download': 'डाउनलोड करें',
    'transaction.dealAccepted': 'सौदा स्वीकार',
    'transaction.produceCollected': 'फसल एकत्रित',
    'transaction.paymentInitiated': 'भुगतान शुरू',
    'transaction.paymentCompleted': 'भुगतान पूर्ण',
    'transaction.perQuintal': 'प्रति क्विंटल',
    'transaction.qualityCheck': 'गुणवत्ता जांच',
    'transaction.weightVerified': 'वजन सत्यापित',
    'transaction.collection': 'संग्रह',
    'transaction.utrNumber': 'UTR संख्या',
    'transaction.farmerAccount': 'किसान खाता',
    'transaction.paymentStatus': 'भुगतान स्थिति',
    'transaction.success': 'सफल',
    'transaction.quintal': 'क्विंटल',
    'transaction.deliveryInfo': 'वितरण जानकारी',
    'transaction.hide': 'छुपाएं',
    'transaction.track': 'ट्रैक करें',
    'transaction.liveTracking': 'लाइव ट्रैकिंग',
    'transaction.currentLocation': 'वर्तमान स्थान',
    'transaction.estimatedArrival': 'अनुमानित पहुंच',
    'transaction.hours': 'घंटे',
    'transaction.journeyComplete': 'यात्रा पूर्ण',
    'transaction.invoice': 'बीजक',
    'transaction.qualityCertificate': 'गुणवत्ता प्रमाण पत्र',
    'transaction.rateTransaction': 'लेन-देन का मूल्यांकन करें',
    'transaction.rateFarmer': 'किसान को रेटिंग दें',
    'transaction.feedback': 'फीडबैक (वैकल्पिक)',
    'transaction.shareExperience': 'अपना अनुभव साझा करें...',
    'transaction.submitRating': 'रेटिंग सबमिट करें',
    'transaction.qualityStatus': 'गुणवत्ता स्थिति',
    'transaction.checkComplete': 'जांच पूर्ण - मानक के अनुसार',
    'transaction.farmerContact': 'किसान संपर्क',
    'transaction.supportCenter': 'सहायता केंद्र',
    'transaction.transportCost': 'परिवहन लागत',
    'transaction.bankTransfer': 'बैंक ट्रांसफर',
    'order.tracking': 'ऑर्डर ट्रैकिंग',
    'order.placed': 'आदेश दिया गया',
    'order.confirmed': 'पुष्ट',
    'order.pendingPayment': 'भुगतान लंबित',
    'order.dispatched': 'भेजा गया',
    'order.delivered': 'डिलीवर',
    'order.paid': 'भुगतान जारी',
    'order.disputed': 'विवादित',
    'order.status.placedDesc': 'किसान द्वारा पुष्टि का इंतजार',
    'order.status.confirmedDesc': 'किसान ने आदेश स्वीकार कर लिया',
    'order.status.pendingPaymentDesc': 'व्यापारी से भुगतान की प्रतीक्षा',
    'order.status.dispatchedDesc': 'फसल रास्ते में है',
    'order.status.deliveredDesc': 'व्यापारी ने प्राप्ति की पुष्टि की',
    'order.status.paidDesc': 'किसान को भुगतान भेज दिया गया',
    'order.status.disputedDesc': 'विवाद समाधान के अधीन',
    'order.confirmOrder': 'आदेश की पुष्टि करें',
    'order.markDispatched': 'भेजा गया के रूप में चिह्नित करें',
    'order.confirmDelivery': 'डिलीवरी प्राप्त की पुष्टि करें',
    'order.payNow': 'अभी भुगतान करें',
    'order.history': 'ऑर्डर इतिहास',
    'order.raiseDispute': 'विवाद उठाएं',
    'order.dispatchDetails': 'डिस्पैच विवरण',
    'order.vehicleNo': 'वाहन संख्या',
    'order.deliveryProof': 'डिलीवरी प्रमाण',
    'order.rateOrder': 'ऑर्डर को रेट करें',
    'order.submitDispute': 'विवाद सबमिट करें',
    'order.confirmDispatch': 'डिस्पैच की पुष्टि करें',
    'order.transportDetails': 'परिवहन विवरण',
    'order.confirmAndPay': 'पुष्टि करें और भुगतान करें',
    'order.disputeUnderReview': 'विवाद की समीक्षा की जा रही है',
    'order.disputeReviewDesc': 'हमारी टीम जांच कर रही है। आपको 24 घंटे के भीतर समाधान मिल जाएगा।',
    'trader.myBids': 'मेरी बोलियां',
    'trader.myBidsDesc': 'मेरी सक्रिय और पिछली बोलियां',
    'trader.totalBids': 'कुल बोलियां लगाई गईं',
    'trader.noBids': 'अभी तक कोई बोली नहीं लगाई गई',
    'trader.visitMarketplace': 'अपनी पहली बोली लगाने के लिए मार्केटप्लेस पर जाएं',
    'trader.yourBid': 'आपकी बोली',
    'trader.hoursAgo': 'घंटे पहले',
    'trader.daysAgo': 'दिन पहले',
    'trader.justNow': 'अभी-अभी',
    'common.rejected': 'अस्वीकार',
    'common.accepted': 'स्वीकार',
    'order.myOrders': 'मेरे ऑर्डर',
    'order.purchases': 'आपकी खरीदारी',
    'order.completedDeals': 'आपके पूर्ण सौदे',
    'order.noOrders': 'अभी तक कोई ऑर्डर नहीं है',
    'order.noOrdersDesc': 'बोली स्वीकार होने के बाद ऑर्डर यहां दिखाई देंगे',
    'order.trader': 'व्यापारी',
    'order.paidLabel': 'भुगतान किया गया',
    'order.loadingOrders': 'आपके ऑर्डर लोड हो रहे हैं...',
    'order.loadingHistory': 'ऑर्डर इतिहास लोड हो रहा है...',
    'bank.addAccount': 'बैंक खाता जोड़ें',
    'bank.chooseBank': 'अपना बैंक चुनें',
    'bank.enterDetails': 'खाते का विवरण दर्ज करें',
    'bank.verifyAccount': 'अपने खाते को सत्यापित करें',
    'bank.securityCheck': 'सुरक्षा सत्यापन',
    'bank.searchBank': 'अपना बैंक खोजें...',
    'bank.popularBanks': 'लोकप्रिय बैंक',
    'bank.allBanks': 'सभी बैंक',
    'bank.accountHolder': 'खाताधारक का नाम',
    'bank.accountNumber': 'खाता संख्या',
    'bank.confirmAccountNumber': 'खाता संख्या की पुष्टि करें',
    'bank.ifscCode': 'IFSC कोड',
    'bank.accountType': 'खाते का प्रकार',
    'bank.savings': 'बचत',
    'bank.current': 'चालू',
    'bank.verifyMyAccount': 'मेरा खाता सत्यापित करें',
    'bank.successTitle': 'बैंक खाता जोड़ दिया गया है!',
    'bank.successDesc': 'आपका खाता सत्यापित और पंजीकृत हो गया है।',
    'bank.continueDashboard': 'डैशबोर्ड पर जारी रखें',
    'produce.addTitle': 'बेचने के लिए उपज जोड़ें',
    'produce.cropName': 'फसल का नाम',
    'produce.selectCrop': 'फसल चुनें',
    'produce.variety': 'किस्म',
    'produce.quantity': 'मात्रा',
    'produce.expectedPrice': 'अपेक्षित मूल्य',
    'produce.images': 'उपज की छवियां',
    'produce.selectFiles': 'फ़ाइलें चुनें',
    'produce.maxImages': 'अधिकतम 5 छवियों की अनुमति है',
    'produce.locationPlaceholder': 'गांव, तहसील, जिला',
    'produce.detectLocation': 'स्थान खोजें',
    'produce.detecting': 'खोज रहे हैं...',
    'produce.description': 'विवरण',
    'produce.descPlaceholder': 'गुणवत्ता, विशेषताएं...',
    'produce.listProduce': 'उपज सूचीबद्ध करें',
    'produce.fillAllFields': 'कृपया सभी आवश्यक फ़ील्ड भरें',
    'farmer.verifyTitle': 'खाता सत्यापन आवश्यक',
    'farmer.verifyPending': 'आपके दस्तावेजों की वर्तमान में एक एडमिन द्वारा समीक्षा की जा रही है। स्वीकृत होने के बाद आप मार्केटप्लेस तक पहुंच पाएंगे।',
    'farmer.verifyRequired': 'जब तक आपकी पहचान सत्यापित नहीं हो जाती, तब तक आप मार्केटप्लेस सुविधाओं का उपयोग नहीं कर सकते। कृपया अपने केवाईसी दस्तावेज अपलोड करने के लिए नीचे प्रोफ़ाइल टैब पर जाएं।',
    'farmer.uploadId': 'अपनी आईडी अपलोड करने के लिए नीचे "प्रोफ़ाइल" टैब पर जाएं!',
    'farmer.activeListings': 'सक्रिय लिस्टिंग और बोलियाँ',
    'farmer.receivedBids': 'प्राप्त बोलियां',
    'farmer.ordersPayments': 'आदेश और भुगतान',
    'farmer.totalEarnings': 'कुल कमाई',
    'farmer.noListings': 'कोई सक्रिय लिस्टिंग नहीं मिली।',
    'farmer.acceptBidTitle': 'बोली स्वीकार करें?',
    'farmer.acceptBidMessage': 'इस बोली को स्वीकार करने से सौदा तय हो जाएगा और इस लिस्टिंग के लिए अन्य सभी प्रस्ताव खारिज कर दिए जाएंगे। जारी रखें?',
    'farmer.confirmPaymentTitle': 'भुगतान प्राप्ति की पुष्टि करें',
    'farmer.confirmPaymentMessage': 'पुष्टि करें कि आपने अपने बैंक खाते में सुरक्षित रूप से भुगतान प्राप्त कर लिया है?',
    'farmer.disputeTitle': 'भुगतान विवाद',
    'farmer.disputeMessage': 'इस भुगतान को प्राप्त नहीं होने के रूप में रिपोर्ट करें? यह ऑर्डर को विवाद के लिए चिह्नित करेगा।',
    'farmer.paymentReceivedDesc': 'व्यापारी ने रेजरपे चेकआउट पूरा कर लिया है! कृपया प्राप्ति की पुष्टि करें।',
    'trader.payConfirm': 'क्या आप Razorpay के माध्यम से इस ऑर्डर के लिए ₹{amount} का भुगतान करना चाहते हैं?',
    'trader.razorpayFail': 'Razorpay SDK लोड करने में विफल रहा। क्या आप ऑनलाइन हैं?',
    'trader.paymentTitle': 'ऑर्डर के लिए भुगतान',
    'trader.verifyTitle': 'खाता सत्यापन आवश्यक',
    'trader.verifyPending': 'आपके दस्तावेजों की एक एडमिन द्वारा समीक्षा की जा रही है। कृपया अनुमोदन की प्रतीक्षा करें।',
    'trader.verifyRequired': 'जब तक आपकी पहचान सत्यापित नहीं हो जाती, तब तक आप मार्केटप्लेस सुविधाओं का उपयोग नहीं कर सकते। कृपया अपने केवाईसी दस्तावेज अपलोड करने के लिए नीचे प्रोफ़ाइल टैब पर जाएं।',
    'trader.uploadId': 'अपनी आईडी अपलोड करने के लिए नीचे "प्रोफ़ाइल" टैब पर जाएं!',
    'trader.activeOrders': 'सक्रिय ऑर्डर और शिपमेंट',
    'trader.noOrders': 'कोई सक्रिय लेनदेन नहीं मिला।',
    'trader.payNow': 'अभी भुगतान करें',
    'trader.paid': 'भुगतान किया गया',
    'trader.marketPulse': 'मार्केट पल्स',
    'trader.noProduce': 'अभी तक कोई नई उपज सूचीबद्ध नहीं है।',
    'trader.availableProduces': 'उपलब्ध फसलें',
    'trader.searchPlaceholder': 'फसल, किस्म या स्थान खोजें...',
    'trader.filters': 'फिल्टर',
    'trader.verifiedOnly': 'केवल सत्यापित',
    'trader.advancedFilters': 'उन्नत फिल्टर',
    'trader.cropType': 'फसल प्रकार',
    'trader.allCrops': 'सभी फसलें',
    'trader.allLocations': 'सभी स्थान',
    'trader.quantityRange': 'मात्रा सीमा',
    'trader.priceRange': 'मूल्य सीमा',
    'trader.min': 'न्यूनतम',
    'trader.max': 'अधिकतम',
    'trader.sortBy': 'क्रमबद्ध करें',
    'trader.newest': 'नवीनतम',
    'trader.priceLow': 'कम कीमत',
    'trader.priceHigh': 'अधिक कीमत',
    'trader.clearFilters': 'सभी फिल्टर साफ़ करें',
    'trader.quickStats': 'त्वरित आंकड़े',
    'trader.minPrice': 'न्यूनतम मूल्य',
    'trader.maxPrice': 'अधिकतम मूल्य',
    
    // Language Selection
    'language.chooseLanguage': 'अपनी भाषा चुनें',
    'language.selectSubtitle': 'कृपया अपनी पसंदीदा भाषा चुनें',
    'language.voiceAssistance': 'आवाज सहायता उपलब्ध',
    'language.tapSpeaker': 'ऑडियो सहायता के लिए स्पीकर आइकन दबाएं',

    // Farmer Dashboard
    'farmer.noConfirmedOrders': 'अभी तक कोई पक्का ऑर्डर नहीं।',
    'farmer.active': 'सक्रिय',
    'farmer.accept': 'स्वीकार करें',
    'farmer.accepting': 'स्वीकार किया जा रहा है...',
    'farmer.yesReceived': 'हाँ, प्राप्त हुआ',
    'farmer.notReceived': 'प्राप्त नहीं हुआ',
    'farmer.basePrice': 'आधार मूल्य',
    'farmer.amount': 'राशि',
    'farmer.trader': 'व्यापारी',
    'farmer.phone': 'फ़ोन',
    'farmer.orderDate': 'ऑर्डर की तारीख',
    'farmer.messageTrader': 'व्यापारी को संदेश भेजें',

    // Trader Dashboard
    'trader.welcome': 'नमस्ते व्यापारी!',
    'trader.purchaseTracking': 'खरीदारी ट्रैकिंग',
    'trader.activeBids': 'सक्रिय बोलियां',
    'trader.availableInMarket': 'बाजार में उपलब्ध',
    'trader.noTransactions': 'अभी तक कोई लेनदेन नहीं।',
    'trader.dealDetails': 'सौदा विवरण',
    'trader.paymentConfirmed': 'भुगतान सफल',
    'trader.awaitingConfirmation': 'किसान की पुष्टि की प्रतीक्षा',
    'trader.paymentDisputed': 'विवादित',
    'trader.pendingPayment': 'भुगतान लंबित',
    'trader.messageFarmer': 'किसान को संदेश भेजें',
  },
  kn: {
    // Common
    'common.continue': 'ಮುಂದುವರಿಸಿ',
    'common.back': 'ಹಿಂದೆ',
    'common.next': 'ಮುಂದೆ',
    'common.previous': 'ಹಿಂದಿನ',
    'common.cancel': 'ರದ್ದುಮಾಡಿ',
    'common.submit': 'ಸಲ್ಲಿಸಿ',
    'common.save': 'ಉಳಿಸಿ',
    'common.edit': 'ಸಂಪಾದಿಸಿ',
    'common.delete': 'ಅಳಿಸಿ',
    'common.search': 'ಹುಡುಕಿ',
    'common.filter': 'ಫಿಲ್ಟರ್',
    'common.all': 'ಎಲ್ಲಾ',
    'common.yes': 'ಹೌದು',
    'common.no': 'ಇಲ್ಲ',
    'common.ok': 'ಸರಿ',
    'common.loading': 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    'common.error': 'ದೋಷ',
    'common.success': 'ಯಶಸ್ಸು',
    
    // Navigation
    'nav.home': 'ಮನೆ',
    'nav.market': 'ಮಾರುಕಟ್ಟೆ',
    'nav.traders': 'ವ್ಯಾಪಾರಿಗಳು',
    'nav.sell': 'ಮಾರಾಟ',
    'nav.buy': 'ಖರೀದಿ',
    'nav.chat': 'ಚಾಟ್',
    'nav.profile': 'ಪ್ರೊಫೈಲ್',
    'nav.verification': 'ಪರಿಶೀಲನೆ',
    'nav.disputes': 'ವಿವಾದಗಳು',
    'nav.prices': 'ಬೆಲೆಗಳು',
    'nav.schemes': 'ಯೋಜನೆಗಳು',
    
    // Auth
    'auth.enterMobile': 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ',
    'auth.verifyOtp': 'OTP ಪರಿಶೀಲಿಸಿ',
    'auth.selectRole': 'ನಿಮ್ಮ ಪಾತ್ರವನ್ನು ಆರಿಸಿ',
    'auth.farmer': 'ನಾನು ರೈತ',
    'auth.trader': 'ನಾನು ವ್ಯಾಪಾರಿ',
    'auth.sendOtp': 'OTP ಕಳುಹಿಸಿ',
    'auth.verifyOtpBtn': 'OTP ಪರಿಶೀಲಿಸಿ',
    'auth.resendOtp': 'OTP ಮರು ಕಳುಹಿಸಿ',
    'auth.farmerDesc': 'ನಿಮ್ಮ ಉತ್ಪನ್ನವನ್ನು ನೇರವಾಗಿ ಮಾರಿ',
    'auth.traderDesc': 'ರೈತರಿಂದ ಉತ್ಪನ್ನ ಖರೀದಿಸಿ',
    
    // Dashboard
    'dashboard.welcome': 'ನಮಸ್ಕಾರ ರೈತರೇ!',
    'dashboard.welcomeTrader': 'ನಮಸ್ಕಾರ ವ್ಯಾಪಾರಿಗಳೇ!',
    'dashboard.activeProducts': 'ಸಕ್ರಿಯ ಉತ್ಪನ್ನಗಳು',
    'dashboard.newBids': 'ಹೊಸ ಬಿಡ್‌ಗಳು',
    'dashboard.availableProduce': 'ಲಭ್ಯವಿರುವ ಉತ್ಪನ್ನ',
    'dashboard.activeBids': 'ಸಕ್ರಿಯ ಬಿಡ್‌ಗಳು',
    'dashboard.quickActions': 'ತ್ವರಿತ ಕ್ರಿಯೆಗಳು',
    'dashboard.sellProduce': 'ಉತ್ಪನ್ನ ಮಾರಿ',
    'dashboard.marketPrices': 'ಮಾರುಕಟ್ಟೆ ಬೆಲೆಗಳು',
    'dashboard.schemes': 'ಯೋಜನೆಗಳು',
    'dashboard.todayPrices': 'ಇಂದಿನ ಮಾರುಕಟ್ಟೆ ಬೆಲೆಗಳು',
    'dashboard.myListedProduce': 'ನನ್ನ ಪಟ್ಟಿ ಮಾಡಿದ ಉತ್ಪನ್ನ',
    'dashboard.recentActivity': 'ಇತ್ತೀಚಿನ ಚಟುವಟಿಕೆ',
    
    // Market
    'market.title': 'ಮಾರುಕಟ್ಟೆ ಬೆಲೆಗಳು',
    'market.liveTitle': 'ನೇರ ಮಾರುಕಟ್ಟೆ ಬೆಲೆಗಳು',
    'market.searchPlaceholder': 'ಬೆಳೆ ಅಥವಾ ಮಂಡಿ ಹುಡುಕಿ',
    'market.rising': 'ಏರುತ್ತಿರುವ',
    'market.falling': 'ಇಳಿಯುತ್ತಿರುವ',
    'market.stable': 'ಸ್ಥಿರ',
    'market.list': 'ಪಟ್ಟಿ',
    'market.compare': 'ಹೋಲಿಕೆ',
    'market.highest': 'ಅತ್ಯಧಿಕ',
    'market.average': 'ಸರಾಸರಿ',
    'market.lowest': 'ಕನಿಷ್ಠ',
    'market.mandiPrices': 'ಮಂಡಿ-ವಾರು ಬೆಲೆಗಳು',
    
    // Add Produce
    'addProduce.title': 'ನಿಮ್ಮ ಉತ್ಪನ್ನ ಮಾರಿ',
    'addProduce.cropDetails': 'ಬೆಳೆ ವಿವರಗಳು',
    'addProduce.pricing': 'ನಿಮ್ಮ ಬೆಲೆ ನಿಗದಿಪಡಿಸಿ',
    'addProduce.locationImages': 'ಸ್ಥಳ ಮತ್ತು ಚಿತ್ರಗಳು',
    'addProduce.review': 'ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಸಲ್ಲಿಸಿ',
    'addProduce.cropName': 'ಬೆಳೆಯ ಹೆಸರು',
    'addProduce.variety': 'ಪ್ರಭೇದ',
    'addProduce.quantity': 'ಪ್ರಮಾಣ',
    'addProduce.minPrice': 'ಕನಿಷ್ಠ ಬೆಲೆ',
    'addProduce.location': 'ಸ್ಥಳ',
    'addProduce.takePhoto': 'ಫೋಟೋ ತೆಗೆಯಿರಿ',
    'addProduce.addToListing': 'ಪಟ್ಟಿಗೆ ಸೇರಿಸಿ',
    
    // Bidding
    'bidding.title': 'ನಿಮ್ಮ ಬಿಡ್ ಇರಿಸಿ',
    'bidding.currentBids': 'ಪ್ರಸ್ತುತ ಬಿಡ್‌ಗಳು',
    'bidding.placeBid': 'ಬಿಡ್ ಇರಿಸಿ',
    'bidding.bidAmount': 'ಬಿಡ್ ಮೊತ್ತ',
    'bidding.message': 'ಸಂದೇಶ (ಐಚ್ಛಿಕ)',
    'bidding.submitBid': 'ಬಿಡ್ ಸಲ್ಲಿಸಿ',
    'bidding.noBids': 'ಇನ್ನೂ ಯಾವುದೇ ಬಿಡ್‌ಗಳಿಲ್ಲ - ಮೊದಲಿಗರಾಗಿ!',
    'bidding.highest': 'ಅತ್ಯಧಿಕ',
    'bidding.totalBids': 'ಒಟ್ಟು ಬಿಡ್‌ಗಳು',
    'bidding.suggestedBid': 'ಸೂಚಿಸಲಾದ ಬಿಡ್',
    'bidding.acceptTitle': 'ಬಿಡ್ ಸ್ವೀಕರಿಸಿ',
    'bidding.acceptBidBtn': 'ಬಿಡ್ ಸ್ವೀಕರಿಸಿ',
    'bidding.acceptWarning': 'ಈ ಬಿಡ್ ಅನ್ನು ಸ್ವೀಕರಿಸುವುದರಿಂದ ಉಳಿದ ಎಲ್ಲಾ ಆಫರ್‌ಗಳನ್ನು ತಿರಸ್ಕರಿಸಲಾಗುತ್ತದೆ ಮತ್ತು ಈ ಪಟ್ಟಿಯನ್ನು ಮಾರಾಟವಾಗಿದೆ ಎಂದು ಗುರುತಿಸಲಾಗುತ್ತದೆ.',

    // Chat
    'chat.typeMessage': 'ಸಂದೇಶ ಟೈಪ್ ಮಾಡಿ...',
    'chat.online': 'ಆನ್‌ಲೈನ್',
    'chat.startConversation': 'ಸಂಭಾಷಣೆ ಪ್ರಾರಂಭಿಸಿ',
    'chat.quickReplies': 'ತ್ವರಿತ ಉತ್ತರಗಳು',
    'chat.interested': 'ಹೌದು, ನನಗೆ ಆಸಕ್ತಿ ಇದೆ',
    'chat.whatPrice': 'ಬೆಲೆ ಎಷ್ಟು?',
    'chat.whenMeet': 'ಯಾವಾಗ ಭೇಟಿಯಾಗಬಹುದು?',
    'chat.thankYou': 'ಧನ್ಯವಾದಗಳು',
    'chat.okay': 'ಸರಿ',
    'chat.talkTomorrow': 'ನಾಳೆ ಮಾತನಾಡೋಣ',
    
    // Profile
    'profile.title': 'ಪ್ರೊಫೈಲ್',
    'profile.phoneNumber': 'ಫೋನ್ ಸಂಖ್ಯೆ',
    'profile.type': 'ಪ್ರಕಾರ',
    'profile.farmer': 'ರೈತ',
    'profile.trader': 'ವ್ಯಾಪಾರಿ',
    'profile.verificationStatus': 'ಪರಿಶೀಲನೆ ಸ್ಥಿತಿ',
    'profile.verified': 'ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
    'profile.notVerified': 'ಪರಿಶೀಲಿಸಲಾಗಿಲ್ಲ',
    'profile.viewSchemes': 'ಸರ್ಕಾರಿ ಯೋಜನೆಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
    
    // Government Schemes
    'schemes.title': 'ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು',
    'schemes.searchPlaceholder': 'ಯೋಜನೆಗಳನ್ನು ಹುಡುಕಿ',
    'schemes.eligibility': 'ಅರ್ಹತೆ',
    'schemes.benefits': 'ಪ್ರಯೋಜನಗಳು',
    'schemes.applyNow': 'ಈಗ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ',
    'schemes.subsidy': 'ಸಬ್ಸಿಡಿ',
    'schemes.loan': 'ಸಾಲ',
    'schemes.insurance': 'ವಿಮೆ',
    'schemes.training': 'ತರಬೇತಿ',
    
    // Transaction
    'transaction.title': 'ವಹಿವಾಟು ಟ್ರ್ಯಾಕಿಂಗ್',
    'transaction.orderId': 'ಆರ್ಡರ್ ಐಡಿ',
    'transaction.amount': 'ಮೊತ್ತ',
    'transaction.quantity': 'ಪ್ರಮಾಣ',
    'transaction.progress': 'ಪ್ರಗತಿ',
    'transaction.pending': 'ಬಾಕಿ',
    'transaction.confirmed': 'ದೃಢೀಕರಿಸಲಾಗಿದೆ',
    'transaction.inTransit': 'ಸಾಗಣೆಯಲ್ಲಿ',
    'transaction.delivered': 'ವಿತರಿಸಲಾಗಿದೆ',
    'transaction.completed': 'ಪೂರ್ಣಗೊಂಡಿದೆ',
    'transaction.needHelp': 'ಸಹಾಯ ಬೇಕೇ?',
    'transaction.contact': 'ಸಂಪರ್ಕಿಸಿ',
    'transaction.summary': 'ವಹಿವಾಟು ಸಾರಾಂಶ',
    'transaction.dealConfirmation': 'ಡೀಲ್ ದೃಢೀಕರಣ',
    'transaction.produce': 'ಉತ್ಪನ್ನ',
    'transaction.rate': 'ದರ',
    'transaction.farmer': 'ರೈತ',
    'transaction.trader': 'ವ್ಯಾಪಾರಿ',
    'transaction.location': 'ಸ್ಥಳ',
    'transaction.qualityGuarantee': 'ಗುಣಮಟ್ಟದ ಖಾತರಿ',
    'transaction.qualityGuaranteeDesc': 'ಉತ್ಪನ್ನದ ಗುಣಮಟ್ಟವನ್ನು ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ ಪರಿಶೀಲಿಸಿದೆ. ಗುಣಮಟ್ಟವು ನಿರೀಕ್ಷೆಯಂತೆ ಇಲ್ಲದಿದ್ದರೆ ಪೂರ್ಣ ಮರುಪಾವತಿ.',
    'transaction.status': 'ಸ್ಥಿತಿ',
    'transaction.trackProgress': 'ನಿಮ್ಮ ವಹಿವಾಟಿನ ಪ್ರಗತಿಯನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
    'transaction.details': 'ವಿವರಗಳು',
    'transaction.viewDetails': 'ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
    'transaction.hideDetails': 'ಮರೆಮಾಡಿ',
    'transaction.paymentBreakdown': 'ಪಾವತಿ ವಿವರಗಳು',
    'transaction.produceValue': 'ಉತ್ಪನ್ನ ಮೌಲ್ಯ',
    'transaction.platformFee': 'ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ ಶುಲ್ಕ',
    'transaction.securePayment': 'ಸುರಕ್ಷಿತ ಪಾವತಿ',
    'transaction.securePaymentDesc': 'ನಿಮ್ಮ ಪಾವತಿಯು ಎಸ್ಕ್ರೊದಲ್ಲಿ ಸುರಕ್ಷಿತವಾಗಿದೆ. ಉತ್ಪನ್ನದ ದೃಢೀಕರಣದ ನಂತರವೇ ರೈತರಿಗೆ ಪಾವತಿಸಲಾಗುವುದು.',
    'transaction.collectionInfo': 'ಸಂಗ್ರಹಣೆ ಮಾಹಿತಿ',
    'transaction.pickupLocation': 'ಸಂಗ್ರಹಣೆ ಸ್ಥಳ',
    'transaction.vehicleDetails': 'ವಾಹನ ವಿವರಗಳು',
    'transaction.driverContact': 'ಚಾಲಕ ಸಂಪರ್ಕ',
    'transaction.receipt': 'ರಶೀದಿ',
    'transaction.download': 'ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ',
    'transaction.dealAccepted': 'ಡೀಲ್ ಸ್ವೀಕರಿಸಲಾಗಿದೆ',
    'transaction.produceCollected': 'ಉತ್ಪನ್ನ ಸಂಗ್ರಹಿಸಲಾಗಿದೆ',
    'transaction.paymentInitiated': 'ಪಾವತಿ ಪ್ರಾರಂಭಿಸಲಾಗಿದೆ',
    'transaction.paymentCompleted': 'ಪಾವತಿ ಪೂರ್ಣಗೊಂಡಿದೆ',
    'transaction.perQuintal': 'ಪ್ರತಿ ಕ್ವಿಂಟಾಲ್‌ಗೆ',
    'transaction.qualityCheck': 'ಗುಣಮಟ್ಟದ ತಪಾಸಣೆ',
    'transaction.weightVerified': 'ತೂಕ ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
    'transaction.collection': 'ಸಂಗ್ರಹಣೆ',
    'transaction.utrNumber': 'UTR ಸಂಖ್ಯೆ',
    'transaction.farmerAccount': 'ರೈತ ಖಾತೆ',
    'transaction.paymentStatus': 'ಪಾವತಿ ಸ್ಥಿತಿ',
    'transaction.success': 'ಯಶಸ್ವಿ',
    'transaction.quintal': 'ಕ್ವಿಂಟಾಲ್',
    'transaction.deliveryInfo': 'ವಿತರಣಾ ಮಾಹಿತಿ',
    'transaction.hide': 'ಮರೆಮಾಡಿ',
    'transaction.track': 'ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
    'transaction.liveTracking': 'ಲೈವ್ ಟ್ರ್ಯಾಕಿಂಗ್',
    'transaction.currentLocation': 'ಪ್ರಸ್ತುತ ಸ್ಥಳ',
    'transaction.estimatedArrival': 'ಅಂದಾಜು ಆಗಮನ',
    'transaction.hours': 'ಗಂಟೆಗಳು',
    'transaction.journeyComplete': 'ಪ್ರಯಾಣ ಪೂರ್ಣಗೊಂಡಿದೆ',
    'transaction.invoice': 'ಇನ್ವಾಯ್ಸ್',
    'transaction.qualityCertificate': 'ಗುಣಮಟ್ಟದ ಪ್ರಮಾಣಪತ್ರ',
    'transaction.rateTransaction': 'ವಹಿವಾಟನ್ನು ರೇಟ್ ಮಾಡಿ',
    'transaction.rateFarmer': 'ರೈತನನ್ನು ರೇಟ್ ಮಾಡಿ',
    'transaction.feedback': 'ಪ್ರತಿಕ್ರಿಯೆ (ಐಚ್ಛಿಕ)',
    'transaction.shareExperience': 'ನಿಮ್ಮ ಅನುಭವವನ್ನು ಹಂಚಿಕೊಳ್ಳಿ...',
    'transaction.submitRating': 'ರೇಟಿಂಗ್ ಸಲ್ಲಿಸಿ',
    'transaction.qualityStatus': 'ಗುಣಮಟ್ಟದ ಸ್ಥಿತಿ',
    'transaction.checkComplete': 'ತಪಾಸಣೆ ಪೂರ್ಣಗೊಂಡಿದೆ - ಮಾನದಂಡಗಳ ಪ್ರಕಾರ',
    'transaction.farmerContact': 'ರೈತ ಸಂಪರ್ಕ',
    'transaction.supportCenter': 'ಬೆಂಬಲ ಕೇಂದ್ರ',
    'transaction.transportCost': 'ಸಾರಿಗೆ ವೆಚ್ಚ',
    'transaction.bankTransfer': 'ಬ್ಯಾಂಕ್ ವರ್ಗಾವಣೆ',
    'order.tracking': 'ಆರ್ಡರ್ ಟ್ರ್ಯಾಕಿಂಗ್',
    'order.placed': 'ಆರ್ಡರ್ ಮಾಡಲಾಗಿದೆ',
    'order.confirmed': 'ದೃಢೀಕರಿಸಲಾಗಿದೆ',
    'order.pendingPayment': 'ಪಾವತಿ ಬಾಕಿ ಇದೆ',
    'order.dispatched': 'ರವಾನಿಸಲಾಗಿದೆ',
    'order.delivered': 'ವಿತರಿಸಲಾಗಿದೆ',
    'order.paid': 'ಪಾವತಿ ಬಿಡುಗಡೆ ಮಾಡಲಾಗಿದೆ',
    'order.disputed': 'ವಿವಾದಿತ',
    'order.status.placedDesc': 'ರೈತರು ದೃಢೀಕರಿಸಲು ಕಾಯುತ್ತಿದ್ದಾರೆ',
    'order.status.confirmedDesc': 'ರೈತರು ಆರ್ಡರ್ ಸ್ವೀಕರಿಸಿದ್ದಾರೆ',
    'order.status.pendingPaymentDesc': 'ವ್ಯಾಪಾರಿಯಿಂದ ಪಾವತಿಗಾಗಿ ಕಾಯಲಾಗುತ್ತಿದೆ',
    'order.status.dispatchedDesc': 'ಉತ್ಪನ್ನವು ದಾರಿಯಲ್ಲಿದೆ',
    'order.status.deliveredDesc': 'ವ್ಯಾಪಾರಿ ಸ್ವೀಕೃತಿಯನ್ನು ದೃಢೀಕರಿಸಿದ್ದಾರೆ',
    'order.status.paidDesc': 'ರೈತರಿಗೆ ಪಾವತಿ ಕಳುಹಿಸಲಾಗಿದೆ',
    'order.status.disputedDesc': 'ವಿವಾದ ಪರಿಹಾರದ ಅಡಿಯಲ್ಲಿದೆ',
    'order.confirmOrder': 'ಆರ್ಡರ್ ದೃಢೀಕರಿಸಿ',
    'order.markDispatched': 'ರವಾನಿಸಲಾಗಿದೆ ಎಂದು ಗುರುತಿಸಿ',
    'order.confirmDelivery': 'ವಿತರಣೆ ಸ್ವೀಕರಿಸಲಾಗಿದೆ ಎಂದು ದೃಢೀಕರಿಸಿ',
    'order.payNow': 'ಈಗ ಪಾವತಿಸಿ',
    'order.history': 'ಆರ್ಡರ್ ಇತಿಹಾಸ',
    'order.raiseDispute': 'ವಿವಾದ ಎತ್ತಿ',
    'order.dispatchDetails': 'ರವಾನೆ ವಿವರಗಳು',
    'order.vehicleNo': 'ವಾಹನ ಸಂಖ್ಯೆ',
    'order.deliveryProof': 'ವಿತರಣಾ ಪುರಾವೆ',
    'order.rateOrder': 'ಆರ್ಡರ್ ರೇಟ್ ಮಾಡಿ',
    'order.submitDispute': 'ವಿವಾದ ಸಲ್ಲಿಸಿ',
    'order.confirmDispatch': 'ರವಾನೆಯನ್ನು ದೃಢೀಕರಿಸಿ',
    'order.transportDetails': 'ಸಾರಿಗೆ ವಿವರಗಳು',
    'order.confirmAndPay': 'ದೃಢೀಕರಿಸಿ ಮತ್ತು ಪಾವತಿಸಲು ಮುಂದುವರಿಯಿರಿ',
    'order.disputeUnderReview': 'ವಿವಾದ ಪರಿಶೀಲನೆಯಲ್ಲಿದೆ',
    'order.disputeReviewDesc': 'ನಮ್ಮ ತಂಡವು ತನಿಖೆ ನಡೆಸುತ್ತಿದೆ. ನೀವು 24 ಗಂಟೆಗಳ ಒಳಗೆ ಪರಿಹಾರವನ್ನು ಪಡೆಯುತ್ತೀರಿ.',
    'trader.myBids': 'ನನ್ನ ಬಿಡ್‌ಗಳು',
    'trader.myBidsDesc': 'ನನ್ನ ಸಕ್ರಿಯ ಮತ್ತು ಹಿಂದಿನ ಬಿಡ್‌ಗಳು',
    'trader.totalBids': 'ಒಟ್ಟು ಬಿಡ್‌ಗಳನ್ನು ಹಾಕಲಾಗಿದೆ',
    'trader.noBids': 'ಇನ್ನೂ ಯಾವುದೇ ಬಿಡ್‌ಗಳನ್ನು ಹಾಕಲಾಗಿಲ್ಲ',
    'trader.visitMarketplace': 'ನಿಮ್ಮ ಮೊದಲ ಬಿಡ್ ಹಾಕಲು ಮಾರುಕಟ್ಟೆಗೆ ಭೇಟಿ ನೀಡಿ',
    'trader.yourBid': 'ನಿಮ್ಮ ಬಿಡ್',
    'trader.hoursAgo': 'ಗಂಟೆಗಳ ಹಿಂದೆ',
    'trader.daysAgo': 'ದಿನಗಳ ಹಿಂದೆ',
    'trader.justNow': 'ಈಗ ತಾನೇ',
    'common.rejected': 'ತಿರಸ್ಕರಿಸಲಾಗಿದೆ',
    'common.accepted': 'ಸ್ವೀಕರಿಸಲಾಗಿದೆ',
    'order.myOrders': 'ನನ್ನ ಆರ್ಡರ್‌ಗಳು',
    'order.purchases': 'ನಿಮ್ಮ ಖರೀದಿಗಳು',
    'order.completedDeals': 'ನಿಮ್ಮ ಪೂರ್ಣಗೊಂಡ ವ್ಯವಹಾರಗಳು',
    'order.noOrders': 'ಇನ್ನೂ ಯಾವುದೇ ಆರ್ಡರ್‌ಗಳಿಲ್ಲ',
    'order.noOrdersDesc': 'ಬಿಡ್ ಸ್ವೀಕರಿಸಿದ ನಂತರ ಆರ್ಡರ್‌ಗಳು ಇಲ್ಲಿ ಕಾಣಿಸಿಕೊಳ್ಳುತ್ತವೆ',
    'order.trader': 'ವ್ಯಾಪಾರಿ',
    'order.paidLabel': 'ಪಾವತಿಸಲಾಗಿದೆ',
    'order.loadingOrders': 'ನಿಮ್ಮ ಆರ್ಡರ್‌ಗಳನ್ನು ಲೋಡ್ ಮಾಡಲಾಗುತ್ತಿದೆ...',
    'order.loadingHistory': 'ಆರ್ಡರ್ ಇತಿಹಾಸ ಲೋಡ್ ಮಾಡಲಾಗುತ್ತಿದೆ...',
    'bank.addAccount': 'ಬ್ಯಾಂಕ್ ಖಾತೆಯನ್ನು ಸೇರಿಸಿ',
    'bank.chooseBank': 'ನಿಮ್ಮ ಬ್ಯಾಂಕ್ ಆಯ್ಕೆಮಾಡಿ',
    'bank.enterDetails': 'ಖಾತೆ ವಿವರಗಳನ್ನು ನಮೂದಿಸಿ',
    'bank.verifyAccount': 'ನಿಮ್ಮ ಖಾತೆಯನ್ನು ಪರಿಶೀಲಿಸಿ',
    'bank.securityCheck': 'ಭದ್ರತಾ ಪರಿಶೀಲನೆ',
    'bank.searchBank': 'ನಿಮ್ಮ ಬ್ಯಾಂಕ್ ಹುಡುಕಿ...',
    'bank.popularBanks': 'ಜನಪ್ರಿಯ ಬ್ಯಾಂಕುಗಳು',
    'bank.allBanks': 'ಎಲ್ಲಾ ಬ್ಯಾಂಕುಗಳು',
    'bank.accountHolder': 'ಖಾತೆದಾರರ ಹೆಸರು',
    'bank.accountNumber': 'ಖಾತೆ ಸಂಖ್ಯೆ',
    'bank.confirmAccountNumber': 'ಖಾತೆ ಸಂಖ್ಯೆಯನ್ನು ದೃಢೀಕರಿಸಿ',
    'bank.ifscCode': 'IFSC ಕೋಡ್',
    'bank.accountType': 'ಖಾತೆ ಪ್ರಕಾರ',
    'bank.savings': 'ಉಳಿತಾಯ',
    'bank.current': 'ಚಾಲ್ತಿ',
    'bank.verifyMyAccount': 'ನನ್ನ ಖಾತೆಯನ್ನು ಪರಿಶೀಲಿಸಿ',
    'bank.successTitle': 'ಬ್ಯಾಂಕ್ ಖಾತೆಯನ್ನು ಸೇರಿಸಲಾಗಿದೆ!',
    'bank.successDesc': 'ನಿಮ್ಮ ಖಾತೆಯನ್ನು ಪರಿಶೀಲಿಸಲಾಗಿದೆ ಮತ್ತು ನೋಂದಾಯಿಸಲಾಗಿದೆ.',
    'bank.continueDashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗೆ ಮುಂದುವರಿಯಿರಿ',
    'produce.addTitle': 'ಮಾರಾಟ ಮಾಡಲು ಉತ್ಪನ್ನವನ್ನು ಸೇರಿಸಿ',
    'produce.cropName': 'ಬೆಳೆ ಹೆಸರು',
    'produce.selectCrop': 'ಬೆಳೆ ಆಯ್ಕೆಮಾಡಿ',
    'produce.variety': 'ತಳಿ',
    'produce.quantity': 'ಪ್ರಮಾಣ',
    'produce.expectedPrice': 'ನಿರೀಕ್ಷಿತ ಬೆಲೆ',
    'produce.images': 'ಉತ್ಪನ್ನದ ಚಿತ್ರಗಳು',
    'produce.selectFiles': 'ಫೈಲ್‌ಗಳನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    'produce.maxImages': 'ಗರಿಷ್ಠ 5 ಚಿತ್ರಗಳಿಗೆ ಅವಕಾಶವಿದೆ',
    'produce.locationPlaceholder': 'ಗ್ರಾಮ, ತಾಲೂಕು, ಜಿಲ್ಲೆ',
    'produce.detectLocation': 'ಸ್ಥಳವನ್ನು ಪತ್ತೆಹಚ್ಚಿ',
    'produce.detecting': 'ಪತ್ತೆಹಚ್ಚಲಾಗುತ್ತಿದೆ...',
    'produce.description': 'ವಿವರಣೆ',
    'produce.descPlaceholder': 'ಗುಣಮಟ್ಟ, ವೈಶಿಷ್ಟ್ಯಗಳು...',
    'produce.listProduce': 'ಉತ್ಪನ್ನವನ್ನು ಪಟ್ಟಿ ಮಾಡಿ',
    'produce.fillAllFields': 'ದಯವಿಟ್ಟು ಎಲ್ಲಾ ಅಗತ್ಯ ಕ್ಷೇತ್ರಗಳನ್ನು ತುಂಬಿ',
    'farmer.verifyTitle': 'ಖಾತೆ ಪರಿಶೀಲನೆ ಅಗತ್ಯವಿದೆ',
    'farmer.verifyPending': 'ನಿಮ್ಮ ದಾಖಲೆಗಳನ್ನು ಪ್ರಸ್ತುತ ಅಡ್ಮಿನ್ ಪರಿಶೀಲಿಸುತ್ತಿದ್ದಾರೆ. ಅನುಮೋದನೆಯ ನಂತರ ನೀವು ಮಾರುಕಟ್ಟೆಯನ್ನು ಪ್ರವೇಶಿಸಲು ಸಾಧ್ಯವಾಗುತ್ತದೆ.',
    'farmer.verifyRequired': 'ನಿಮ್ಮ ಗುರುತು ಪರಿಶೀಲನೆಯಾಗುವವರೆಗೆ ನೀವು ಮಾರುಕಟ್ಟೆ ವೈಶಿಷ್ಟ್ಯಗಳನ್ನು ಪ್ರವೇಶಿಸಲು ಸಾಧ್ಯವಿಲ್ಲ. ನಿಮ್ಮ KYC ದಾಖಲೆಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಲು ದಯವಿಟ್ಟು ಕೆಳಗಿನ ಪ್ರೊಫೈಲ್ ಟ್ಯಾಬ್‌ಗೆ ಹೋಗಿ.',
    'farmer.uploadId': 'ನಿಮ್ಮ ಐಡಿ ಅಪ್‌ಲೋಡ್ ಮಾಡಲು ಕೆಳಗಿನ "ಪ್ರೊಫೈಲ್" ಟ್ಯಾಬ್‌ಗೆ ಹೋಗಿ!',
    'farmer.activeListings': 'ಸಕ್ರಿಯ ಪಟ್ಟಿಗಳು ಮತ್ತು ಬಿಡ್‌ಗಳು',
    'farmer.receivedBids': 'ಸ್ವೀಕರಿಸಿದ ಬಿಡ್‌ಗಳು',
    'farmer.ordersPayments': 'ಆದೇಶಗಳು ಮತ್ತು ಪಾವತಿಗಳು',
    'farmer.totalEarnings': 'ಒಟ್ಟು ಗಳಿಕೆ',
    'farmer.noListings': 'ಯಾವುದೇ ಸಕ್ರಿಯ ಪಟ್ಟಿಗಳು ಕಂಡುಬಂದಿಲ್ಲ.',
    'farmer.acceptBidTitle': 'ಬೆಲೆಯನ್ನು ಒಪ್ಪಿಕೊಳ್ಳುವುದೇ?',
    'farmer.acceptBidMessage': 'ಈ ಬೆಲೆಯನ್ನು ಒಪ್ಪಿಕೊಳ್ಳುವುದರಿಂದ ವ್ಯವಹಾರ ಅಂತಿಮಗೊಳ್ಳುತ್ತದೆ ಮತ್ತು ಈ ಪಟ್ಟಿಯ ಇತರ ಎಲ್ಲಾ ಆಫರ್‌ಗಳನ್ನು ತಿರಸ್ಕರಿಸಲಾಗುತ್ತದೆ. ಮುಂದುವರಿಯಬೇಕೆ?',
    'farmer.confirmPaymentTitle': 'ಪಾವತಿ ಸ್ವೀಕೃತಿಯನ್ನು ದೃಢೀಕರಿಸಿ',
    'farmer.confirmPaymentMessage': 'ನಿಮ್ಮ ಬ್ಯಾಂಕ್ ಖಾತೆಯಲ್ಲಿ ನೀವು ಪಾವತಿಯನ್ನು ಸುರಕ್ಷಿತವಾಗಿ ಸ್ವೀಕರಿಸಿದ್ದೀರಿ ಎಂದು ದೃಢೀಕರಿಸುವಿರಾ?',
    'farmer.disputeTitle': 'ಪಾವತಿ ವಿವಾದ',
    'farmer.disputeMessage': 'ಈ ಪಾವತಿಯನ್ನು ಸ್ವೀಕರಿಸಲಾಗಿಲ್ಲ ಎಂದು ವರದಿ ಮಾಡುವಿರಾ? ಇದು ವಿವಾದಕ್ಕಾಗಿ ಆರ್ಡರ್ ಅನ್ನು ಗುರುತಿಸುತ್ತದೆ.',
    'farmer.paymentReceivedDesc': 'ವ್ಯಾಪಾರಿ ರೇಜರ್‌ಪೇ ಚೆಕ್‌ಔಟ್ ಪೂರ್ಣಗೊಳಿಸಿದ್ದಾರೆ! ದಯವಿಟ್ಟು ಸ್ವೀಕೃತಿಯನ್ನು ದೃಢೀಕರಿಸಿ.',
    'trader.payConfirm': 'ರೇಜರ್‌ಪೇ ಮೂಲಕ ಈ ಆರ್ಡರ್‌ಗಾಗಿ ₹{amount} ಪಾವತಿಸಲು ಮುಂದುವರಿಯುವಿರಾ?',
    'trader.razorpayFail': 'ರೇಜರ್‌ಪೇ SDK ಲೋಡ್ ಮಾಡಲು ವಿಫಲವಾಗಿದೆ. ನೀವು ಆನ್‌ಲೈನ್‌ನಲ್ಲಿದ್ದೀರಾ?',
    'trader.paymentTitle': 'ಆರ್ಡರ್‌ಗಾಗಿ ಪಾವತಿ',
    'trader.verifyTitle': 'ಖಾತೆ ಪರಿಶೀಲನೆ ಅಗತ್ಯವಿದೆ',
    'trader.verifyPending': 'ನಿಮ್ಮ ದಾಖಲೆಗಳನ್ನು ಅಡ್ಮಿನ್ ಪರಿಶೀಲಿಸುತ್ತಿದ್ದಾರೆ. ದಯವಿಟ್ಟು ಅನುಮೋದನೆಗಾಗಿ ಕಾಯಿರಿ.',
    'trader.verifyRequired': 'ನಿಮ್ಮ ಗುರುತು ಪರಿಶೀಲನೆಯಾಗುವವರೆಗೆ ನೀವು ಮಾರುಕಟ್ಟೆ ವೈಶಿಷ್ಟ್ಯಗಳನ್ನು ಪ್ರವೇಶಿಸಲು ಸಾಧ್ಯವಿಲ್ಲ. ನಿಮ್ಮ KYC ದಾಖಲೆಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಲು ದಯವಿಟ್ಟು ಕೆಳಗಿನ ಪ್ರೊಫೈಲ್ ಟ್ಯಾಬ್‌ಗೆ ಹೋಗಿ.',
    'trader.uploadId': 'ನಿಮ್ಮ ಐಡಿ ಅಪ್‌ಲೋಡ್ ಮಾಡಲು ಕೆಳಗಿನ "ಪ್ರೊಫೈಲ್" ಟ್ಯಾಬ್‌ಗೆ ಹೋಗಿ!',
    'trader.activeOrders': 'ಸಕ್ರಿಯ ಆರ್ಡರ್‌ಗಳು ಮತ್ತು ಸಾಗಣೆಗಳು',
    'trader.noOrders': 'ಯಾವುದೇ ಸಕ್ರಿಯ ವಹಿವಾಟುಗಳು ಕಂಡುಬಂದಿಲ್ಲ.',
    'trader.payNow': 'ಈಗ ಪಾವತಿಸಿ',
    'trader.paid': 'ಪಾವತಿಸಲಾಗಿದೆ',
    'trader.marketPulse': 'ಮಾರುಕಟ್ಟೆ ನಾಡಿಮಿಡಿತ',
    'trader.noProduce': 'ಇನ್ನೂ ಯಾವುದೇ ಹೊಸ ಉತ್ಪನ್ನ ಪಟ್ಟಿಯಾಗಿಲ್ಲ.',
    'trader.availableProduces': 'ಲಭ್ಯವಿರುವ ಉತ್ಪನ್ನಗಳು',
    'trader.searchPlaceholder': 'ಬೆಳೆಗಳು, ತಳಿ ಅಥವಾ ಸ್ಥಳವನ್ನು ಹುಡುಕಿ...',
    'trader.filters': 'ಫಿಲ್ಟರ್‌ಗಳು',
    'trader.verifiedOnly': 'ಪರಿಶೀಲಿಸಿದವು ಮಾತ್ರ',
    'trader.advancedFilters': 'ಸುಧಾರಿತ ಫಿಲ್ಟರ್‌ಗಳು',
    'trader.cropType': 'ಬೆಳೆ ಪ್ರಕಾರ',
    'trader.allCrops': 'ಎಲ್ಲಾ ಬೆಳೆಗಳು',
    'trader.allLocations': 'ಎಲ್ಲಾ ಸ್ಥಳಗಳು',
    'trader.quantityRange': 'ಪ್ರಮಾಣದ ಶ್ರೇಣಿ',
    'trader.priceRange': 'ಬೆಲೆ ಶ್ರೇಣಿ',
    'trader.min': 'ಕನಿಷ್ಠ',
    'trader.max': 'ಗರಿಷ್ಠ',
    'trader.sortBy': 'ಹೀಗೆ ವಿಂಗಡಿಸಿ',
    'trader.newest': 'ಹೊಸದು ಮೊದಲು',
    'trader.priceLow': 'ಬೆಲೆ: ಕಡಿಮೆಯಿಂದ ಹೆಚ್ಚು',
    'trader.priceHigh': 'ಬೆಲೆ: ಹೆಚ್ಚಿನಿಂದ ಕಡಿಮೆ',
    'trader.clearFilters': 'ಎಲ್ಲಾ ಫಿಲ್ಟರ್‌ಗಳನ್ನು ತೆಗೆದುಹಾಕಿ',
    'trader.quickStats': 'ತ್ವರಿತ ಅಂಕಿಅಂಶಗಳು',
    'trader.minPrice': 'ಕನಿಷ್ಠ ಬೆಲೆ',
    'trader.maxPrice': 'ಗರಿಷ್ಠ ಬೆಲೆ',
    
    // Language Selection
    'language.chooseLanguage': 'ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಆರಿಸಿ',
    'language.selectSubtitle': 'ದಯವಿಟ್ಟು ನಿಮ್ಮ ಆದ್ಯತೆಯ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    'language.voiceAssistance': 'ಧ್ವನಿ ಸಹಾಯ ಲಭ್ಯವಿದೆ',
    'language.tapSpeaker': 'ಆಡಿಯೋ ಸಹಾಯಕ್ಕಾಗಿ ಸ್ಪೀಕರ್ ಐಕಾನ್ ಟ್ಯಾಪ್ ಮಾಡಿ',

    // Farmer Dashboard
    'farmer.noConfirmedOrders': 'ಇನ್ನೂ ಯಾವುದೇ ಆರ್ಡರ್ ಇಲ್ಲ.',
    'farmer.active': 'ಸಕ್ರಿಯ',
    'farmer.accept': 'ಸ್ವೀಕರಿಸಿ',
    'farmer.accepting': 'ಸ್ವೀಕರಿಸಲಾಗುತ್ತಿದೆ...',
    'farmer.yesReceived': 'ಹೌದು, ಸ್ವೀಕರಿಸಲಾಗಿದೆ',
    'farmer.notReceived': 'ಸ್ವೀಕರಿಸಲಾಗಿಲ್ಲ',
    'farmer.basePrice': 'ಮೂಲ ಬೆಲೆ',
    'farmer.amount': 'ಮೊತ್ತ',
    'farmer.trader': 'ವ್ಯಾಪಾರಿ',
    'farmer.phone': 'ಫೋನ್',
    'farmer.orderDate': 'ಆರ್ಡರ್ ದಿನಾಂಕ',
    'farmer.messageTrader': 'ವ್ಯಾಪಾರಿಗಳಿಗೆ ಸಂದೇಶ ಕಳುಹಿಸಿ',

    // Trader Dashboard
    'trader.welcome': 'ನಮಸ್ಕಾರ ವ್ಯಾಪಾರಿಗಳೇ!',
    'trader.purchaseTracking': 'ಖರೀದಿ ಟ್ರ್ಯಾಕಿಂಗ್',
    'trader.activeBids': 'ಸಕ್ರಿಯ ಬಿಡ್‌ಗಳು',
    'trader.availableInMarket': 'ಮಾರುಕಟ್ಟೆಯಲ್ಲಿ ಲಭ್ಯವಿದೆ',
    'trader.noTransactions': 'ಇನ್ನೂ ಯಾವುದೇ ವಹಿವಾಟು ಇಲ್ಲ.',
    'trader.dealDetails': 'ಸೌಧ ವಿವರಗಳು',
    'trader.paymentConfirmed': 'ಪಾವತಿ ಯಶಸ್ವಿಯಾಗಿದೆ',
    'trader.awaitingConfirmation': 'ರೈತರ ದೃಢೀಕರಣಕ್ಕಾಗಿ ಕಾಯಲಾಗುತ್ತಿದೆ',
    'trader.paymentDisputed': 'ವಿವಾದದಲ್ಲಿದೆ',
    'trader.pendingPayment': 'ಪಾವತಿ ಬಾಕಿ ಇದೆ',
    'trader.messageFarmer': 'ರೈತರಿಗೆ ಸಂದೇಶ ಕಳುಹಿಸಿ',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('selectedLanguage');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('selectedLanguage', language);
  }, [language]);

  const t = (key: string): string => {
    return (translations[language] as any)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};